export const stockSymbols = [
  { symbol: "AAPL", companyName: "Apple Inc." },
  { symbol: "MSFT", companyName: "Microsoft Corporation" },
  { symbol: "GOOG", companyName: "Alphabet Inc." },
  { symbol: "GOOGL", companyName: "Alphabet Inc." },
  { symbol: "AMZN", companyName: "Amazon.com, Inc." },
  { symbol: "NVDA", companyName: "NVIDIA Corporation" },
  { symbol: "BRK.A", companyName: "Berkshire Hathaway Inc." },
  { symbol: "BRK.B", companyName: "Berkshire Hathaway Inc." },
  { symbol: "META", companyName: "Meta Platforms, Inc." },
  { symbol: "TSLA", companyName: "Tesla, Inc." },
  { symbol: "V", companyName: "Visa Inc." },
  { symbol: "UNH", companyName: "UnitedHealth Group Incorporated" },
  {
    symbol: "TSM",
    companyName: "Taiwan Semiconductor Manufacturing Company Limited",
  },
  { symbol: "LLY", companyName: "Eli Lilly and Company" },
  { symbol: "XOM", companyName: "Exxon Mobil Corporation" },
  { symbol: "JNJ", companyName: "Johnson & Johnson" },
  { symbol: "WMT", companyName: "Walmart Inc." },
  { symbol: "JPM", companyName: "JPMorgan Chase & Co." },
  { symbol: "NVO", companyName: "Novo Nordisk A/S" },
  { symbol: "PG", companyName: "The Procter & Gamble Company" },
  { symbol: "MA", companyName: "Mastercard Incorporated" },
  { symbol: "MRK", companyName: "Merck & Co., Inc." },
  { symbol: "CVX", companyName: "Chevron Corporation" },
  { symbol: "HD", companyName: "The Home Depot, Inc." },
  { symbol: "KO", companyName: "The Coca-Cola Company" },
  { symbol: "AVGO", companyName: "Broadcom Inc." },
  { symbol: "PEP", companyName: "PepsiCo, Inc." },
  { symbol: "ORCL", companyName: "Oracle Corporation" },
  { symbol: "ASML", companyName: "ASML Holding N.V." },
  { symbol: "ABBV", companyName: "AbbVie Inc." },
  { symbol: "AZN", companyName: "AstraZeneca PLC" },
  { symbol: "BABA", companyName: "Alibaba Group Holding Limited" },
  { symbol: "COST", companyName: "Costco Wholesale Corporation" },
  { symbol: "BAC", companyName: "Bank of America Corporation" },
  { symbol: "NVS", companyName: "Novartis AG" },
  { symbol: "BHP", companyName: "BHP Group Limited" },
  { symbol: "MCD", companyName: "McDonald's Corporation" },
  { symbol: "PFE", companyName: "Pfizer Inc." },
  { symbol: "SHEL", companyName: "Shell plc" },
  { symbol: "TMO", companyName: "Thermo Fisher Scientific Inc." },
  { symbol: "CRM", companyName: "Salesforce, Inc." },
  { symbol: "CSCO", companyName: "Cisco Systems, Inc." },
  { symbol: "TM", companyName: "Toyota Motor Corporation" },
  { symbol: "ABT", companyName: "Abbott Laboratories" },
  { symbol: "NKE", companyName: "NIKE, Inc." },
  { symbol: "DIS", companyName: "The Walt Disney Company" },
  { symbol: "FMX", companyName: "Fomento Económico Mexicano, SAB de CV" },
  { symbol: "LIN", companyName: "Linde plc" },
  { symbol: "ACN", companyName: "Accenture plc" },
  { symbol: "TMUS", companyName: "T-Mobile US, Inc." },
  { symbol: "DHR", companyName: "Danaher Corporation" },
  { symbol: "CMCSA", companyName: "Comcast Corporation" },
  { symbol: "AMD", companyName: "Advanced Micro Devices, Inc." },
  { symbol: "ADBE", companyName: "Adobe Inc." },
  { symbol: "SAP", companyName: "SAP SE" },
  { symbol: "NEE", companyName: "NextEra Energy, Inc." },
  { symbol: "VZ", companyName: "Verizon Communications Inc." },
  { symbol: "HSBC", companyName: "HSBC Holdings plc" },
  { symbol: "NFLX", companyName: "Netflix, Inc." },
  { symbol: "TXN", companyName: "Texas Instruments Incorporated" },
  { symbol: "PM", companyName: "Philip Morris International Inc." },
  { symbol: "TTE", companyName: "TotalEnergies SE" },
  { symbol: "WFC", companyName: "Wells Fargo & Company" },
  { symbol: "UPS", companyName: "United Parcel Service, Inc." },
  { symbol: "BMY", companyName: "Bristol-Myers Squibb Company" },
  { symbol: "RTX", companyName: "Raytheon Technologies Corporation" },
  { symbol: "MS", companyName: "Morgan Stanley" },
  { symbol: "SNY", companyName: "Sanofi" },
  { symbol: "UL", companyName: "Unilever PLC" },
  { symbol: "RY", companyName: "Royal Bank of Canada" },
  { symbol: "HON", companyName: "Honeywell International Inc." },
  { symbol: "INTC", companyName: "Intel Corporation" },
  { symbol: "HDB", companyName: "HDFC Bank Limited" },
  { symbol: "AMGN", companyName: "Amgen Inc." },
  { symbol: "BA", companyName: "The Boeing Company" },
  { symbol: "SBUX", companyName: "Starbucks Corporation" },
  { symbol: "UNP", companyName: "Union Pacific Corporation" },
  { symbol: "LOW", companyName: "Lowe's Companies, Inc." },
  { symbol: "COP", companyName: "ConocoPhillips" },
  { symbol: "BUD", companyName: "Anheuser-Busch InBev SA/NV" },
  { symbol: "MDT", companyName: "Medtronic plc" },
  { symbol: "INTU", companyName: "Intuit Inc." },
  { symbol: "T", companyName: "AT&T Inc." },
  { symbol: "SONY", companyName: "Sony Group Corporation" },
  { symbol: "QCOM", companyName: "QUALCOMM Incorporated" },
  { symbol: "SPGI", companyName: "S&P Global Inc." },
  { symbol: "LMT", companyName: "Lockheed Martin Corporation" },
  { symbol: "IBM", companyName: "International Business Machines Corporation" },
  { symbol: "PLD", companyName: "Prologis, Inc." },
  { symbol: "TD", companyName: "The Toronto-Dominion Bank" },
  { symbol: "AXP", companyName: "American Express Company" },
  { symbol: "GE", companyName: "General Electric Company" },
  { symbol: "SYK", companyName: "Stryker Corporation" },
  { symbol: "DE", companyName: "Deere & Company" },
  { symbol: "ISRG", companyName: "Intuitive Surgical, Inc." },
  { symbol: "BP", companyName: "BP p.l.c." },
  { symbol: "CAT", companyName: "Caterpillar Inc." },
  { symbol: "GS", companyName: "The Goldman Sachs Group, Inc." },
  { symbol: "MDLZ", companyName: "Mondelez International, Inc." },
  { symbol: "ELV", companyName: "Elevance Health Inc." },
  { symbol: "AMAT", companyName: "Applied Materials, Inc." },
  { symbol: "DEO", companyName: "Diageo plc" },
  { symbol: "RIO", companyName: "Rio Tinto Group" },
  { symbol: "BKNG", companyName: "Booking Holdings Inc." },
  { symbol: "GILD", companyName: "Gilead Sciences, Inc." },
  { symbol: "BX", companyName: "Blackstone Inc." },
  { symbol: "NOW", companyName: "ServiceNow, Inc." },
  { symbol: "BLK", companyName: "BlackRock, Inc." },
  { symbol: "ADI", companyName: "Analog Devices, Inc." },
  { symbol: "TJX", companyName: "The TJX Companies, Inc." },
  { symbol: "MMC", companyName: "Marsh & McLennan Companies, Inc." },
  { symbol: "AMT", companyName: "American Tower Corporation" },
  { symbol: "VRTX", companyName: "Vertex Pharmaceuticals Incorporated" },
  { symbol: "SCHW", companyName: "The Charles Schwab Corporation" },
  { symbol: "C", companyName: "Citigroup Inc." },
  { symbol: "ADP", companyName: "Automatic Data Processing, Inc." },
  { symbol: "PDD", companyName: "PDD Holdings Inc." },
  { symbol: "CVS", companyName: "CVS Health Corporation" },
  { symbol: "EQNR", companyName: "Equinor ASA" },
  { symbol: "ZTS", companyName: "Zoetis Inc." },
  { symbol: "CB", companyName: "Chubb Limited" },
  { symbol: "MUFG", companyName: "Mitsubishi UFJ Financial Group, Inc." },
  { symbol: "MO", companyName: "Altria Group, Inc." },
  { symbol: "IBN", companyName: "ICICI Bank Limited" },
  { symbol: "REGN", companyName: "Regeneron Pharmaceuticals, Inc." },
  { symbol: "SO", companyName: "The Southern Company" },
  { symbol: "CNI", companyName: "Canadian National Railway Company" },
  { symbol: "SHOP", companyName: "Shopify Inc." },
  { symbol: "ENB", companyName: "Enbridge Inc." },
  { symbol: "BSX", companyName: "Boston Scientific Corporation" },
  { symbol: "CP", companyName: "Canadian Pacific Railway Limited" },
  { symbol: "PBR", companyName: "Petróleo Brasileiro S.A. - Petrobras" },
  { symbol: "PGR", companyName: "The Progressive Corporation" },
  { symbol: "HCA", companyName: "HCA Healthcare, Inc." },
  { symbol: "UBER", companyName: "Uber Technologies, Inc." },
  { symbol: "CI", companyName: "Cigna Corporation" },
  { symbol: "BTI", companyName: "British American Tobacco p.l.c." },
  { symbol: "LRCX", companyName: "Lam Research Corporation" },
  { symbol: "GSK", companyName: "GSK plc" },
  { symbol: "FISV", companyName: "Fiserv, Inc." },
  { symbol: "AMX", companyName: "América Móvil, SAB de CV" },
  { symbol: "DUK", companyName: "Duke Energy Corporation" },
  { symbol: "TGT", companyName: "Target Corporation" },
  { symbol: "ABNB", companyName: "Airbnb, Inc." },
  { symbol: "BDX", companyName: "Becton, Dickinson and Company" },
  { symbol: "EL", companyName: "The Estée Lauder Companies Inc." },
  { symbol: "MU", companyName: "Micron Technology, Inc." },
  { symbol: "PBR.A", companyName: "Petróleo Brasileiro S.A. - Petrobras" },
  { symbol: "ITW", companyName: "Illinois Tool Works Inc." },
  { symbol: "WM", companyName: "Waste Management, Inc." },
  { symbol: "ABB", companyName: "ABB Ltd" },
  { symbol: "PYPL", companyName: "PayPal Holdings, Inc." },
  { symbol: "AON", companyName: "Aon plc" },
  { symbol: "CL", companyName: "Colgate-Palmolive Company" },
  { symbol: "EQIX", companyName: "Equinix, Inc." },
  { symbol: "ETN", companyName: "Eaton Corporation plc" },
  { symbol: "NOC", companyName: "Northrop Grumman Corporation" },
  { symbol: "CME", companyName: "CME Group Inc." },
  { symbol: "HUM", companyName: "Humana Inc." },
  { symbol: "CSX", companyName: "CSX Corporation" },
  { symbol: "SLB", companyName: "Schlumberger Limited" },
  { symbol: "MELI", companyName: "MercadoLibre, Inc." },
  { symbol: "EOG", companyName: "EOG Resources, Inc." },
  { symbol: "MNST", companyName: "Monster Beverage Corporation" },
  { symbol: "INFY", companyName: "Infosys Limited" },
  { symbol: "BMO", companyName: "Bank of Montreal" },
  { symbol: "APD", companyName: "Air Products and Chemicals, Inc." },
  { symbol: "ATVI", companyName: "Activision Blizzard, Inc." },
  { symbol: "ICE", companyName: "Intercontinental Exchange, Inc." },
  { symbol: "VALE", companyName: "Vale S.A." },
  { symbol: "CNQ", companyName: "Canadian Natural Resources Limited" },
  { symbol: "NTES", companyName: "NetEase, Inc." },
  { symbol: "JD", companyName: "JD.com, Inc." },
  { symbol: "UBS", companyName: "UBS Group AG" },
  { symbol: "TRI", companyName: "Thomson Reuters Corporation" },
  { symbol: "RELX", companyName: "RELX PLC" },
  { symbol: "BNS", companyName: "The Bank of Nova Scotia" },
  { symbol: "PANW", companyName: "Palo Alto Networks, Inc." },
  { symbol: "SCCO", companyName: "Southern Copper Corporation" },
  { symbol: "SHW", companyName: "The Sherwin-Williams Company" },
  { symbol: "SNPS", companyName: "Synopsys, Inc." },
  { symbol: "ORLY", companyName: "O'Reilly Automotive, Inc." },
  { symbol: "GD", companyName: "General Dynamics Corporation" },
  { symbol: "CMG", companyName: "Chipotle Mexican Grill, Inc." },
  { symbol: "SMFG", companyName: "Sumitomo Mitsui Financial Group, Inc." },
  { symbol: "MCO", companyName: "Moody's Corporation" },
  { symbol: "EPD", companyName: "Enterprise Products Partners L.P." },
  { symbol: "KLAC", companyName: "KLA Corporation" },
  { symbol: "SNOW", companyName: "Snowflake Inc." },
  { symbol: "FDX", companyName: "FedEx Corporation" },
  { symbol: "CDNS", companyName: "Cadence Design Systems, Inc." },
  { symbol: "HSY", companyName: "The Hershey Company" },
  { symbol: "SAN", companyName: "Banco Santander, S.A." },
  { symbol: "KKR", companyName: "KKR & Co. Inc." },
  { symbol: "MCK", companyName: "McKesson Corporation" },
  { symbol: "MMM", companyName: "3M Company" },
  { symbol: "EW", companyName: "Edwards Lifesciences Corporation" },
  { symbol: "FTNT", companyName: "Fortinet, Inc." },
  { symbol: "NGG", companyName: "National Grid plc" },
  { symbol: "RACE", companyName: "Ferrari N.V." },
  { symbol: "ITUB", companyName: "Itaú Unibanco Holding S.A." },
  { symbol: "GIS", companyName: "General Mills, Inc." },
  { symbol: "TAK", companyName: "Takeda Pharmaceutical Company Limited" },
  { symbol: "MAR", companyName: "Marriott International, Inc." },
  { symbol: "VMW", companyName: "VMware, Inc." },
  { symbol: "OXY", companyName: "Occidental Petroleum Corporation" },
  { symbol: "KVUE", companyName: "Kenvue Inc." },
  { symbol: "BN", companyName: "Brookfield Corporation" },
  { symbol: "PSA", companyName: "Public Storage" },
  { symbol: "FCX", companyName: "Freeport-McMoRan Inc." },
  { symbol: "CHTR", companyName: "Charter Communications, Inc." },
  { symbol: "STLA", companyName: "Stellantis N.V." },
  { symbol: "AZO", companyName: "AutoZone, Inc." },
  { symbol: "ECL", companyName: "Ecolab Inc." },
  { symbol: "ROP", companyName: "Roper Technologies, Inc." },
  { symbol: "MSI", companyName: "Motorola Solutions, Inc." },
  { symbol: "KMB", companyName: "Kimberly-Clark Corporation" },
  { symbol: "NSC", companyName: "Norfolk Southern Corporation" },
  { symbol: "CCI", companyName: "Crown Castle Inc." },
  { symbol: "WDAY", companyName: "Workday, Inc." },
  { symbol: "KHC", companyName: "The Kraft Heinz Company" },
  { symbol: "E", companyName: "Eni S.p.A." },
  { symbol: "LULU", companyName: "Lululemon Athletica Inc." },
  { symbol: "MRNA", companyName: "Moderna, Inc." },
  { symbol: "CTAS", companyName: "Cintas Corporation" },
  { symbol: "DG", companyName: "Dollar General Corporation" },
  { symbol: "PXD", companyName: "Pioneer Natural Resources Company" },
  { symbol: "AJG", companyName: "Arthur J. Gallagher & Co." },
  { symbol: "HMC", companyName: "Honda Motor Co., Ltd." },
  { symbol: "LVS", companyName: "Las Vegas Sands Corp." },
  { symbol: "RSG", companyName: "Republic Services, Inc." },
  { symbol: "BIDU", companyName: "Baidu, Inc." },
  { symbol: "EMR", companyName: "Emerson Electric Co." },
  { symbol: "ABEV", companyName: "Ambev S.A." },
  { symbol: "ING", companyName: "ING Groep N.V." },
  { symbol: "DXCM", companyName: "DexCom, Inc." },
  { symbol: "MPC", companyName: "Marathon Petroleum Corporation" },
  { symbol: "SRE", companyName: "Sempra" },
  { symbol: "AEP", companyName: "American Electric Power Company, Inc." },
  { symbol: "BSBR", companyName: "Banco Santander (Brasil) S.A." },
  { symbol: "KDP", companyName: "Keurig Dr Pepper Inc." },
  { symbol: "PNC", companyName: "The PNC Financial Services Group, Inc." },
  { symbol: "BIIB", companyName: "Biogen Inc." },
  { symbol: "APH", companyName: "Amphenol Corporation" },
  { symbol: "TDG", companyName: "TransDigm Group Incorporated" },
  { symbol: "F", companyName: "Ford Motor Company" },
  { symbol: "D", companyName: "Dominion Energy, Inc." },
  { symbol: "USB", companyName: "U.S. Bancorp" },
  { symbol: "GM", companyName: "General Motors Company" },
  { symbol: "NXPI", companyName: "NXP Semiconductors N.V." },
  { symbol: "BCE", companyName: "BCE Inc." },
  { symbol: "WDS", companyName: "Woodside Energy Group Ltd" },
  { symbol: "PSX", companyName: "Phillips 66" },
  { symbol: "TRV", companyName: "The Travelers Companies, Inc." },
  { symbol: "JCI", companyName: "Johnson Controls International plc" },
  { symbol: "ANET", companyName: "Arista Networks, Inc." },
  { symbol: "PCG", companyName: "PG&E Corporation" },
  { symbol: "STZ", companyName: "Constellation Brands, Inc." },
  { symbol: "ADSK", companyName: "Autodesk, Inc." },
  { symbol: "PH", companyName: "Parker-Hannifin Corporation" },
  { symbol: "SE", companyName: "Sea Limited" },
  { symbol: "IDXX", companyName: "IDEXX Laboratories, Inc." },
  { symbol: "BBVA", companyName: "Banco Bilbao Vizcaya Argentaria, S.A." },
  { symbol: "O", companyName: "Realty Income Corporation" },
  { symbol: "MCHP", companyName: "Microchip Technology Incorporated" },
  { symbol: "CTVA", companyName: "Corteva, Inc." },
  { symbol: "HLN", companyName: "Haleon plc" },
  { symbol: "TRP", companyName: "TC Energy Corporation" },
  { symbol: "HES", companyName: "Hess Corporation" },
  { symbol: "ADM", companyName: "Archer-Daniels-Midland Company" },
  { symbol: "VLO", companyName: "Valero Energy Corporation" },
  { symbol: "ALC", companyName: "Alcon Inc." },
  { symbol: "TT", companyName: "Trane Technologies plc" },
  { symbol: "AFL", companyName: "Aflac Incorporated" },
  { symbol: "EXC", companyName: "Exelon Corporation" },
  { symbol: "ET", companyName: "Energy Transfer LP" },
  { symbol: "PUK", companyName: "Prudential plc" },
  { symbol: "YUM", companyName: "Yum! Brands, Inc." },
  { symbol: "SPG", companyName: "Simon Property Group, Inc." },
  { symbol: "CPRT", companyName: "Copart, Inc." },
  { symbol: "WELL", companyName: "Welltower Inc." },
  { symbol: "STM", companyName: "STMicroelectronics N.V." },
  { symbol: "PAYX", companyName: "Paychex, Inc." },
  { symbol: "DHI", companyName: "D.R. Horton, Inc." },
  { symbol: "MFG", companyName: "Mizuho Financial Group, Inc." },
  { symbol: "CM", companyName: "Canadian Imperial Bank of Commerce" },
  { symbol: "AIG", companyName: "American International Group, Inc." },
  { symbol: "TEL", companyName: "TE Connectivity Ltd." },
  { symbol: "HLT", companyName: "Hilton Worldwide Holdings Inc." },
  { symbol: "MET", companyName: "MetLife, Inc." },
  { symbol: "A", companyName: "Agilent Technologies, Inc." },
  { symbol: "NEM", companyName: "Newmont Corporation" },
  { symbol: "SYY", companyName: "Sysco Corporation" },
  { symbol: "SU", companyName: "Suncor Energy Inc." },
  { symbol: "PCAR", companyName: "PACCAR Inc" },
  { symbol: "LYG", companyName: "Lloyds Banking Group plc" },
  { symbol: "MFC", companyName: "Manulife Financial Corporation" },
  { symbol: "XEL", companyName: "Xcel Energy Inc." },
  { symbol: "KMI", companyName: "Kinder Morgan, Inc." },
  { symbol: "WCN", companyName: "Waste Connections, Inc." },
  { symbol: "MSCI", companyName: "MSCI Inc." },
  { symbol: "TEAM", companyName: "Atlassian Corporation Plc" },
  { symbol: "TFC", companyName: "Truist Financial Corporation" },
  { symbol: "CRH", companyName: "CRH plc" },
  { symbol: "DOW", companyName: "Dow Inc." },
  { symbol: "CNC", companyName: "Centene Corporation" },
  { symbol: "ON", companyName: "ON Semiconductor Corporation" },
  { symbol: "MRVL", companyName: "Marvell Technology, Inc." },
  { symbol: "IQV", companyName: "IQVIA Holdings Inc." },
  { symbol: "GEHC", companyName: "GE HealthCare Technologies Inc." },
  { symbol: "ABC", companyName: "AmerisourceBergen Corporation" },
  { symbol: "ROST", companyName: "Ross Stores, Inc." },
  { symbol: "APO", companyName: "Apollo Global Management, Inc." },
  { symbol: "CARR", companyName: "Carrier Global Corporation" },
  { symbol: "SGEN", companyName: "Seagen Inc." },
  { symbol: "DLTR", companyName: "Dollar Tree, Inc." },
  { symbol: "KR", companyName: "The Kroger Co." },
  { symbol: "WMB", companyName: "The Williams Companies, Inc." },
  { symbol: "LHX", companyName: "L3Harris Technologies, Inc." },
  { symbol: "LNG", companyName: "Cheniere Energy, Inc." },
  { symbol: "SQ", companyName: "Block, Inc." },
  { symbol: "COF", companyName: "Capital One Financial Corporation" },
  { symbol: "NUE", companyName: "Nucor Corporation" },
  { symbol: "EA", companyName: "Electronic Arts Inc." },
  { symbol: "OTIS", companyName: "Otis Worldwide Corporation" },
  { symbol: "GOLD", companyName: "Barrick Gold Corporation" },
  { symbol: "MPLX", companyName: "MPLX LP" },
  { symbol: "BBD", companyName: "Banco Bradesco S.A." },
  { symbol: "RMD", companyName: "ResMed Inc." },
  { symbol: "ED", companyName: "Consolidated Edison, Inc." },
  { symbol: "GWW", companyName: "W.W. Grainger, Inc." },
  { symbol: "AME", companyName: "AMETEK, Inc." },
  { symbol: "ORAN", companyName: "Orange S.A." },
  { symbol: "QSR", companyName: "Restaurant Brands International Inc." },
  { symbol: "DELL", companyName: "Dell Technologies Inc." },
  { symbol: "PPG", companyName: "PPG Industries, Inc." },
  { symbol: "NTR", companyName: "Nutrien Ltd." },
  { symbol: "ODFL", companyName: "Old Dominion Freight Line, Inc." },
  { symbol: "TTD", companyName: "The Trade Desk, Inc." },
  { symbol: "LEN.B", companyName: "Lennar Corporation" },
  { symbol: "CRWD", companyName: "CrowdStrike Holdings, Inc." },
  {
    symbol: "FIS",
    companyName: "Fidelity National Information Services, Inc.",
  },
  { symbol: "LEN", companyName: "Lennar Corporation" },
  { symbol: "ILMN", companyName: "Illumina, Inc." },
  { symbol: "CHT", companyName: "Chunghwa Telecom Co., Ltd." },
  { symbol: "VRSK", companyName: "Verisk Analytics, Inc." },
  { symbol: "CTSH", companyName: "Cognizant Technology Solutions Corporation" },
  { symbol: "BK", companyName: "The Bank of New York Mellon Corporation" },
  { symbol: "NWG", companyName: "NatWest Group plc" },
  { symbol: "VICI", companyName: "VICI Properties Inc." },
  { symbol: "IBKR", companyName: "Interactive Brokers Group, Inc." },
  { symbol: "ROK", companyName: "Rockwell Automation, Inc." },
  { symbol: "AMP", companyName: "Ameriprise Financial, Inc." },
  { symbol: "CSGP", companyName: "CoStar Group, Inc." },
  { symbol: "WBD", companyName: "Warner Bros. Discovery, Inc." },
  {
    symbol: "PEG",
    companyName: "Public Service Enterprise Group Incorporated",
  },
  { symbol: "ALL", companyName: "The Allstate Corporation" },
  { symbol: "FAST", companyName: "Fastenal Company" },
  { symbol: "CCEP", companyName: "Coca-Cola Europacific Partners PLC" },
  { symbol: "BF.A", companyName: "Brown-Forman Corporation" },
  { symbol: "CVE", companyName: "Cenovus Energy Inc." },
  { symbol: "BF.B", companyName: "Brown-Forman Corporation" },
  { symbol: "MTD", companyName: "Mettler-Toledo International Inc." },
  { symbol: "HPQ", companyName: "HP Inc." },
  { symbol: "MBLY", companyName: "Mobileye Global Inc." },
  { symbol: "CMI", companyName: "Cummins Inc." },
  { symbol: "DD", companyName: "DuPont de Nemours, Inc." },
  { symbol: "FERG", companyName: "Ferguson plc" },
  { symbol: "BCS", companyName: "Barclays PLC" },
  { symbol: "GFS", companyName: "GLOBALFOUNDRIES Inc." },
  { symbol: "DVN", companyName: "Devon Energy Corporation" },
  { symbol: "FNV", companyName: "Franco-Nevada Corporation" },
  { symbol: "BBDO", companyName: "Banco Bradesco S.A." },
  { symbol: "SPOT", companyName: "Spotify Technology S.A." },
  { symbol: "TU", companyName: "TELUS Corporation" },
  { symbol: "LI", companyName: "Li Auto Inc." },
  { symbol: "CPNG", companyName: "Coupang, Inc." },
  { symbol: "NU", companyName: "Nu Holdings Ltd." },
  { symbol: "AEM", companyName: "Agnico Eagle Mines Limited" },
  { symbol: "SLF", companyName: "Sun Life Financial Inc." },
  { symbol: "LYB", companyName: "LyondellBasell Industries N.V." },
  { symbol: "PRU", companyName: "Prudential Financial, Inc." },
  { symbol: "WEC", companyName: "WEC Energy Group, Inc." },
  { symbol: "DLR", companyName: "Digital Realty Trust, Inc." },
  { symbol: "ZBH", companyName: "Zimmer Biomet Holdings, Inc." },
  { symbol: "AWK", companyName: "American Water Works Company, Inc." },
  { symbol: "DDOG", companyName: "Datadog, Inc." },
  { symbol: "BKR", companyName: "Baker Hughes Company" },
  { symbol: "ACGL", companyName: "Arch Capital Group Ltd." },
  { symbol: "VOD", companyName: "Vodafone Group PLC" },
  {
    symbol: "TLK",
    companyName:
      "Perusahaan Perseroan (Persero) PT Telekomunikasi Indonesia Tbk",
  },
  { symbol: "VEEV", companyName: "Veeva Systems Inc." },
  { symbol: "GMAB", companyName: "Genmab A/S" },
  { symbol: "WBA", companyName: "Walgreens Boots Alliance, Inc." },
  { symbol: "EIX", companyName: "Edison International" },
  { symbol: "NDAQ", companyName: "Nasdaq, Inc." },
  { symbol: "IMO", companyName: "Imperial Oil Limited" },
  { symbol: "RCI", companyName: "Rogers Communications Inc." },
  { symbol: "GPN", companyName: "Global Payments Inc." },
  { symbol: "WST", companyName: "West Pharmaceutical Services, Inc." },
  { symbol: "KEYS", companyName: "Keysight Technologies, Inc." },
  { symbol: "GLW", companyName: "Corning Incorporated" },
  { symbol: "DASH", companyName: "DoorDash, Inc." },
  { symbol: "ES", companyName: "Eversource Energy" },
  { symbol: "HAL", companyName: "Halliburton Company" },
  { symbol: "TEF", companyName: "Telefónica, S.A." },
  { symbol: "VMC", companyName: "Vulcan Materials Company" },
  { symbol: "ANSS", companyName: "ANSYS, Inc." },
  { symbol: "YUMC", companyName: "Yum China Holdings, Inc." },
  { symbol: "CEG", companyName: "Constellation Energy Corporation" },
  { symbol: "WIT", companyName: "Wipro Limited" },
  { symbol: "BNTX", companyName: "BioNTech SE" },
  { symbol: "IT", companyName: "Gartner, Inc." },
  { symbol: "OKE", companyName: "ONEOK, Inc." },
  { symbol: "SBAC", companyName: "SBA Communications Corporation" },
  { symbol: "ULTA", companyName: "Ulta Beauty, Inc." },
  { symbol: "BGNE", companyName: "BeiGene, Ltd." },
  { symbol: "MLM", companyName: "Martin Marietta Materials, Inc." },
  { symbol: "EFX", companyName: "Equifax Inc." },
  { symbol: "AVB", companyName: "AvalonBay Communities, Inc." },
  { symbol: "TSCO", companyName: "Tractor Supply Company" },
  { symbol: "PWR", companyName: "Quanta Services, Inc." },
  { symbol: "APTV", companyName: "Aptiv PLC" },
  { symbol: "GIB", companyName: "CGI Inc." },
  { symbol: "ARES", companyName: "Ares Management Corporation" },
  { symbol: "DFS", companyName: "Discover Financial Services" },
  { symbol: "WTW", companyName: "Willis Towers Watson PLC" },
  { symbol: "ALB", companyName: "Albemarle Corporation" },
  { symbol: "K", companyName: "Kellogg Company" },
  { symbol: "ALNY", companyName: "Alnylam Pharmaceuticals, Inc." },
  { symbol: "MKC", companyName: "McCormick & Company, Incorporated" },
  { symbol: "IR", companyName: "Ingersoll Rand Inc." },
  { symbol: "RBLX", companyName: "Roblox Corporation" },
  { symbol: "HUBS", companyName: "HubSpot, Inc." },
  { symbol: "TROW", companyName: "T. Rowe Price Group, Inc." },
  { symbol: "CHD", companyName: "Church & Dwight Co., Inc." },
  { symbol: "VRSN", companyName: "VeriSign, Inc." },
  { symbol: "ZTO", companyName: "ZTO Express (Cayman) Inc." },
  { symbol: "GPC", companyName: "Genuine Parts Company" },
  { symbol: "ALGN", companyName: "Align Technology, Inc." },
  { symbol: "EQR", companyName: "Equity Residential" },
  { symbol: "TECK", companyName: "Teck Resources Limited" },
  { symbol: "CQP", companyName: "Cheniere Energy Partners, L.P." },
  { symbol: "EBAY", companyName: "eBay Inc." },
  { symbol: "RYAAY", companyName: "Ryanair Holdings plc" },
  { symbol: "CDW", companyName: "CDW Corporation" },
  { symbol: "CBRE", companyName: "CBRE Group, Inc." },
  { symbol: "FTV", companyName: "Fortive Corporation" },
  { symbol: "FSLR", companyName: "First Solar, Inc." },
  { symbol: "DTE", companyName: "DTE Energy Company" },
  { symbol: "FANG", companyName: "Diamondback Energy, Inc." },
  { symbol: "ARGX", companyName: "argenx SE" },
  { symbol: "WPM", companyName: "Wheaton Precious Metals Corp." },
  { symbol: "BAX", companyName: "Baxter International Inc." },
  { symbol: "URI", companyName: "United Rentals, Inc." },
  { symbol: "PODD", companyName: "Insulet Corporation" },
  { symbol: "STT", companyName: "State Street Corporation" },
  { symbol: "UDR", companyName: "UDR, Inc." },
  { symbol: "ENPH", companyName: "Enphase Energy, Inc." },
  { symbol: "HZNP", companyName: "Horizon Therapeutics PLC" },
  { symbol: "NOK", companyName: "Nokia Oyj" },
  { symbol: "TCOM", companyName: "Trip.com Group Limited" },
  { symbol: "AEE", companyName: "Ameren Corporation" },
  { symbol: "FE", companyName: "FirstEnergy Corp." },
  { symbol: "CAH", companyName: "Cardinal Health, Inc." },
  { symbol: "HEI", companyName: "HEICO Corporation" },
  { symbol: "ETR", companyName: "Entergy Corporation" },
  { symbol: "DAL", companyName: "Delta Air Lines, Inc." },
  { symbol: "EXR", companyName: "Extra Space Storage Inc." },
  { symbol: "HEI.A", companyName: "HEICO Corporation" },
  { symbol: "DB", companyName: "Deutsche Bank Aktiengesellschaft" },
  { symbol: "IFF", companyName: "International Flavors & Fragrances Inc." },
  { symbol: "HIG", companyName: "The Hartford Financial Services Group, Inc." },
  { symbol: "WY", companyName: "Weyerhaeuser Company" },
  { symbol: "FTS", companyName: "Fortis Inc." },
  { symbol: "HRL", companyName: "Hormel Foods Corporation" },
  { symbol: "BEKE", companyName: "KE Holdings Inc." },
  { symbol: "SQM", companyName: "Sociedad Química y Minera de Chile S.A." },
  { symbol: "PLTR", companyName: "Palantir Technologies Inc." },
  { symbol: "TTWO", companyName: "Take-Two Interactive Software, Inc." },
  { symbol: "IX", companyName: "ORIX Corporation" },
  { symbol: "CLX", companyName: "The Clorox Company" },
  { symbol: "ELP", companyName: "Companhia Paranaense de Energia - COPEL" },
  { symbol: "PKX", companyName: "POSCO Holdings Inc." },
  { symbol: "ROL", companyName: "Rollins, Inc." },
  { symbol: "STE", companyName: "STERIS plc" },
  { symbol: "RTO", companyName: "Rentokil Initial plc" },
  { symbol: "UMC", companyName: "United Microelectronics Corporation" },
  { symbol: "ARE", companyName: "Alexandria Real Estate Equities, Inc." },
  { symbol: "INVH", companyName: "Invitation Homes Inc." },
  { symbol: "PPL", companyName: "PPL Corporation" },
  { symbol: "MT", companyName: "ArcelorMittal S.A." },
  { symbol: "HOLX", companyName: "Hologic, Inc." },
  { symbol: "MPWR", companyName: "Monolithic Power Systems, Inc." },
  { symbol: "ZM", companyName: "Zoom Video Communications, Inc." },
  { symbol: "AIU", companyName: "Meta Data Limited" },
  { symbol: "GRMN", companyName: "Garmin Ltd." },
  { symbol: "RCL", companyName: "Royal Caribbean Cruises Ltd." },
  { symbol: "MTB", companyName: "M&T Bank Corporation" },
  { symbol: "MDB", companyName: "MongoDB, Inc." },
];
